# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "geo-autocomplete"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-03-30"
  s.description = "Geo-autocomplete wrapped as a Rails 3 engine for easy use"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "demo/geo-autocomplete/config/addresses.de.yml",
    "demo/geo-autocomplete/config/geo_keys.yml",
    "demo/geo-autocomplete/geocode_app.rb",
    "demo/geo-autocomplete/helpers.rb",
    "demo/javascript/geocode/geocode_app.js",
    "demo/javascript/geocode/geocode_field.js",
    "demo/javascript/geocode/geocode_init.js",
    "demo/javascript/simple_geocoder.js",
    "demo/ui.demo.html",
    "lib/geo-autocomplete.rb",
    "vendor/assets/javascripts/ui.geo_autocomplete.js",
    "vendor/assets/javascripts/ui.geo_autocomplete_alt.debug.js",
    "vendor/assets/javascripts/ui.geo_autocomplete_alt.js"
  ]
  s.homepage = "http://github.com/kristianmandrup/geo-autocomplete"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.20"
  s.summary = "Geo-autocomplete for Rails 3.1+"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

