# use with GeoCodeApp

de:
  munich:
    - Mullerstrasse 43 
    - Rosenheimerstrasse 108
    - Marienplatz 14
    - Karlzplatz 32
    - Maximilianstrasse 7
    - Burkleinstrasse 1
    - Bruderstrasse 15
    - Maxburgstrasse 12
    - Rindermarkt 2
    - Marienstrasse 10
    - Reitmorstrasse 6
    - Pilotystrasse 11
    - Maxburgstrasse 9
    - Salvatorstrasse 10
    - Odeonsplatz 8
    - Elisenstrasse 7
